version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: books-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: booksdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - books-network

  # Books API Application
  books-api:
    build: .
    container_name: books-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/booksdb?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - books-network
    volumes:
      - ./public:/app/public:ro

volumes:
  mongodb_data:

networks:
  books-network:
    driver: bridge