services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: books-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: booksdb

  # Books API Application
  books-api:
    build: .
    container_name: books-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/booksdb
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./public:/app/public:ro

volumes:
  mongodb_data: